# Usage Example
version: '3'

services:
  nginx:
    image: ichikawayukko/nginx_letsencrypt:1.17.10-alpine 
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./volume/htdocs/:/var/www/html/:z
      - ./volume/certs/:/etc/letsencrypt/:z
    ports:
      - "80:80"
      - "443:443"
    restart: always
